version: '3.8'

services:
  db:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_DB: "${DB_NAME}"
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      ALLOW_IP_RANGE: '0.0.0.0/0'
    command: [ "postgres", "-c", "log_statement=all", "-c", "logging_collector=on", "-c", "log_directory=pg_logs", "-c", "log_filename=postgresql-%Y-%m-%d_%H%M%S.log" ]
    networks:
      - fullstack
    ports:
      - 5432:5432
    restart: always

networks:
  fullstack:
    driver: bridge
